sigatp/src/main/java/br/gov/jfrj/siga/tp/model/EscalaDeTrabalho.java
package br.gov.jfrj.siga.tp.model;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Collections;
import java.util.Iterator;
import java.util.List;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.NoResultException;
import javax.persistence.OneToMany;
import javax.persistence.Query;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import org.hibernate.envers.Audited;

import br.gov.jfrj.siga.feature.converter.entity.vraptor.ConvertableEntity;
import br.gov.jfrj.siga.model.ActiveRecord;

@Entity
@Audited
@Table(schema = "SIGATP")
public class EscalaDeTrabalho extends TpModel implements ConvertableEntity  {

	private static final long serialVersionUID = 1L;
	public static final ActiveRecord<EscalaDeTrabalho> AR = new ActiveRecord<>(EscalaDeTrabalho.class);

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "hibernate_sequence_generator")
	@SequenceGenerator(name = "hibernate_sequence_generator", sequenceName = "SIGATP.hibernate_sequence")
	private long id;

	@NotNull
	private Calendar dataVigenciaInicio;

	private Calendar dataVigenciaFim;

	@ManyToOne
	@NotNull
	private Condutor condutor;

	@NotNull(message = "Inclua ao menos um dia de trabalho na escala")
	@OneToMany(mappedBy = "escalaDeTrabalho")
	private List<DiaDeTrabalho> diasDeTrabalho;

	public EscalaDeTrabalho() {
		this.id = 0;
		this.diasDeTrabalho = new ArrayList<DiaDeTrabalho>();
	}

	@Override
	public Long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Calendar getDataVigenciaInicio() {
		return dataVigenciaInicio;
	}

	public void setDataVigenciaInicio(Calendar dataVigenciaInicio) {
		this.dataVigenciaInicio = dataVigenciaInicio;
	}

	public Calendar getDataVigenciaFim() {
		return dataVigenciaFim;
	}

	public void setDataVigenciaFim(Calendar dataVigenciaFim) {
		this.dataVigenciaFim = dataVigenciaFim;
	}

	public Condutor getCondutor() {
		return condutor;
	}

	public void setCondutor(Condutor condutor) {
		this.condutor = condutor;
	}

	public List<DiaDeTrabalho> getDiasDeTrabalho() {
		return diasDeTrabalho;
	}

	public void setDiasDeTrabalho(List<DiaDeTrabalho> diasDeTrabalho) {
		this.diasDeTrabalho = diasDeTrabalho;
	}

	public void iniciarVigencia() {
		this.dataVigenciaInicio = Calendar.getInstance();
	}

	public void encerrarVigencia() {
		this.dataVigenciaFim = Calendar.getInstance();
	}

	public static List<EscalaDeTrabalho> buscarTodosPorCondutor(Condutor condutor) {
		return EscalaDeTrabalho.AR.find("condutor = ? ORDER BY dataVigenciaInicio DESC, dataVigenciaFim DESC", condutor).fetch();		
	}

	public static List<EscalaDeTrabalho> buscarTodasVigentes() {
		StringBuffer hqlVigentes = new StringBuffer();
		hqlVigentes.append("dataVigenciaInicio < current_date ");
		hqlVigentes.append("and ((dataVigenciaFim is null) or (dataVigenciaFim > current_date)) ");
		hqlVigentes.append("order by dataVigenciaInicio ");
		return EscalaDeTrabalho.AR.find(hqlVigentes.toString()).<EscalaDeTrabalho> fetch();
	}

	public String getEscalaParaExibicao() {
		StringBuffer saida = new StringBuffer();
		boolean primeiro = true;

		if (diasDeTrabalho != null) {
			Collections.sort(diasDeTrabalho);
			for (Iterator<DiaDeTrabalho> iterator = diasDeTrabalho.iterator(); iterator.hasNext();) {
				if (primeiro) {
					primeiro = false;
				} else {
					saida.append("; ");
				}
				DiaDeTrabalho dia = iterator.next();
				saida.append(dia.toString());
			}
		}

		return saida.toString();
	}

	public Boolean estaEscaladoNesteDia(String data) throws ParseException {
		for (DiaDeTrabalho diaDeTrabalho : diasDeTrabalho) {
			Calendar horaSaidaMissao = Calendar.getInstance();

			SimpleDateFormat formatar = new SimpleDateFormat("dd/MM/yyyy HH:mm");
			horaSaidaMissao.setTime(formatar.parse(data));
			SimpleDateFormat formatarHora = new SimpleDateFormat("HHmm");
			String strHoraSaidaMissao = formatarHora.format(horaSaidaMissao.getTime());

			String dataSaidaMissao = String.valueOf(DiaDaSemana.getDiaDaSemana(data).getOrdem()) + strHoraSaidaMissao;

			if (Integer.parseInt(dataSaidaMissao) >= Integer.parseInt(diaDeTrabalho.getDiaEntrada().getOrdem() + diaDeTrabalho.getHoraEntradaFormatada("HHmm"))
					&& Integer.parseInt(dataSaidaMissao) <= Integer.parseInt(diaDeTrabalho.getDiaSaida().getOrdem() + diaDeTrabalho.getHoraSaidaFormatada("HHmm"))) {
				return true;
			}
		}
		return false;
	}

	@SuppressWarnings("unchecked")
	public static List<EscalaDeTrabalho> buscarPorCondutores(Long idCondutor, String dataHoraInicio) {

		String filtroCondutor = "";
		if (idCondutor != null) {
			filtroCondutor = "condutor.id = " + idCondutor + " AND ";
		}

		String dataFormatadaOracle = "to_date('" + dataHoraInicio + "', 'DD/MM/YYYY')";
		List<EscalaDeTrabalho> escalas;

		String qrl = "SELECT e FROM EscalaDeTrabalho e WHERE " + filtroCondutor + " DATE(dataVigenciaInicio) <= DATE(" + dataFormatadaOracle + ")"
				+ " AND (dataVigenciaFim IS NULL OR DATE(dataVigenciaFim) >= DATE(" + dataFormatadaOracle + "))";

		Query qry = AR.em().createQuery(qrl);
		try {
			escalas = (List<EscalaDeTrabalho>) qry.getResultList();
		} catch (NoResultException ex) {
			escalas = null;
		}
		return escalas;
	}
	
					
	
	
	
	
	
}

sigatp/src/main/java/br/gov/jfrj/siga/tp/model/Grupo.java
package br.gov.jfrj.siga.tp.model;

import java.util.Collections;
import java.util.List;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import org.hibernate.annotations.Immutable;
import org.hibernate.envers.Audited;

import br.gov.jfrj.siga.feature.converter.entity.vraptor.ConvertableEntity;
import br.gov.jfrj.siga.model.ActiveRecord;
import br.gov.jfrj.siga.tp.validation.annotation.UpperCase;

@Entity
@Audited
@Immutable
@Table(name = "GRUPOVEICULO", schema = "SIGATP")
public class Grupo extends TpModel implements ConvertableEntity, Comparable<Grupo> {

	private static final long serialVersionUID = -3681022838391034811L;

	public static final ActiveRecord<Grupo> AR = new ActiveRecord<>(Grupo.class);

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "hibernate_sequence_generator")
	@SequenceGenerator(name = "hibernate_sequence_generator", sequenceName = "SIGATP.hibernate_sequence")
	private long id;

	@NotNull
	@UpperCase
	private String nome;

	@NotNull
	@UpperCase
	private String finalidade;

	@NotNull
	@UpperCase
	private String caracteristicas;

	@NotNull
	@UpperCase
	private String letra;

	public Grupo() {
		this.nome = "";
		this.finalidade = "";
		this.caracteristicas = "";
	}

	public String getDadosParaExibicao() {
		return this.letra.toUpperCase() + "-" + this.nome.toUpperCase();
	}

	public int compareTo(Grupo g) {
		return this.letra.compareTo(g.letra);
	}

	@SuppressWarnings("unchecked")
	public static List<Grupo> listarTodos() throws Exception {
		List<Grupo> grupos = Grupo.AR.findAll();
		Collections.sort(grupos);
		return grupos;
	}

	@Override
	public Long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getFinalidade() {
		return finalidade;
	}

	public void setFinalidade(String finalidade) {
		this.finalidade = finalidade;
	}

	public String getCaracteristicas() {
		return caracteristicas;
	}

	public void setCaracteristicas(String caracteristicas) {
		this.caracteristicas = caracteristicas;
	}

	public String getLetra() {
		return letra;
	}

	public void setLetra(String letra) {
		this.letra = letra;
	}
}

sigatp/src/main/webapp/WEB-INF/page/escalaDeTrabalho/editar.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>
<%@ taglib uri="http://localhost/jeetags" prefix="siga" %>

<siga:pagina titulo="Transportes">
	<div class="gt-bd clearfix">
		<div class="gt-content clearfix">
			<h2>${escala.condutor.dadosParaExibicao} - <fmt:message key="${modo}" /> <fmt:message key="escalaDeTrabalho" /></h2>
			<jsp:include page="form.jsp" />
		</div>
	</div>
</siga:pagina>

sigatp/src/main/webapp/WEB-INF/page/escalaDeTrabalho/escalas.jsp
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<script src="${pageContext.request.contextPath}/public/javascripts/jquery/jquery-1.6.4.min.js"></script>
<script src="${pageContext.request.contextPath}/public/javascripts/jquery/jquery-ui-1.8.16.custom.min.js"></script>
<script src="${pageContext.request.contextPath}/public/javascripts/jquery/i18n/jquery.ui.datepicker-pt-BR.js"></script>
<script src="${pageContext.request.contextPath}/public/javascripts/jquery.maskedinput-1.2.2.min.js"></script>
<link rel="stylesheet" href="${pageContext.request.contextPath}/public/javascripts/jquery/jquery-ui-1.8.16.custom.css" type="text/css" media="screen">

<script>
	var escalas = {};
	
	escalas.componentes = function(){
		escalas.salvar = document.getElementById('salvar');
		escalas.finalizar = document.getElementById('finalizar');
		escalas.cancelar = document.getElementById('cancelar');
		escalas.incluir = document.getElementById("btn-Incluir-DiasDeTrabalho");
		
		escalas.formulario = document.getElementById('formEscalasDeTrabalho');
		escalas.exluir = document.getElementsByName('linkExcluirSelecionados');
	};
	
	escalas.init = function(){
		escalas.componentes();
		
		escalas.salvar.addEventListener("click", function(){
				escalas.submitForm(urlSalvar);
			});
	
		escalas.finalizar.addEventListener('click', function(){
				escalas.submitForm(urlFinalizar);
			});
	
		escalas.cancelar.addEventListener('click', function(){
				window.location = urlCancelar;
			});
	
		escalas.incluir.addEventListener('click', function(){
				var divrow = document.getElementById("rowDiasDeTrabalho");
				var htmlNaoSelecionado = divrow.innerHTML;
				var htmlSelecionado = htmlNaoSelecionado.replace(/naoSelecionado/g, "selecionado");
				var html = '<tr>';
				html = html	+ '<th width="15%" class="obrigatorio">Dia Inicio / Fim </th>';
				html = html + '<td>';
				html = html + htmlSelecionado;
				html = html + '</td>';
				html = html	+ '<td width="8%" ><a class="linkExcluir" name="linkExcluirSelecionados" onclick="escalas.apagaLinha(this)" style="display:inline" href="#">Excluir</a></td>';
				html = html + '</tr>';
	
				$("#htmlgridDiasDeTrabalho tbody").append(html);
				carregarMascaraHora();
			});
	};
	
	escalas.submitForm = function(acao) {
		escalas.formulario.setAttribute('action', acao);
		escalas.formulario.setAttribute('method', 'GET');
		var idxSelect = 0;
		var isSelect = false;
		var x = 0;
		var inputsDiaDeTrabalho =  $('.selecionado');
		for (var i = 0; i < inputsDiaDeTrabalho.length; i++)
		{
			var nome = inputsDiaDeTrabalho[i].name;
			if(nome === undefined) {
				isSelect = true;
				nome = $(inputsDiaDeTrabalho[i]).parent()[idxSelect].name;
			}
			x = ~~(i / 5); 
			var nomeCompleto = (nome == "id") ? "diasDeTrabalho[" + x + "]" : "diasDeTrabalho[" + x + "]." + nome;
			
			if(isSelect) {
				isSelect = false;
				if(nome != nomeCompleto)
					$(inputsDiaDeTrabalho[i]).parent()[idxSelect].setAttribute("name", nomeCompleto);
			} else
				if(nome != nomeCompleto)
					inputsDiaDeTrabalho[i].setAttribute("name", nomeCompleto);
		}
	
	 	var tbodydiadetrabalho = document.getElementById("tbody");
	 	escalas.formulario.submit();
	};
	
	escalas.escapeRegExp = function(str) {
		return str.replace(/[\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g, "\\$&");
	};
	
	escalas.replaceAll = function(find, replace, str) {
		return str.replace(new RegExp(escalas.escapeRegExp(find), 'g'), replace);
	};
	
	escalas.apagaLinha = function(link) {
		if ($(link).attr('disabled'))
			return false;
	
		var html = "";
		if (confirm('Tem certeza de que deseja excluir este dia?')) {
			var trExcluir = link.parentNode.parentNode;
			var tabela = trExcluir.parentNode;
			tabela.removeChild(trExcluir);
		}
	};
	
	$(function() {
		escalas.init();
	});
</script>

sigatp/src/main/webapp/WEB-INF/page/escalaDeTrabalho/form.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>

<script type="text/javascript" src="/sigatp/public/javascripts/validacao.js"></script>

<script type="text/javascript">
	var urlSalvar = '<c:out value="${linkTo[EscalaDeTrabalhoController].salvar}" />';
	var urlFinalizar = '<c:out value="${linkTo[EscalaDeTrabalhoController].finalizar}" />';
	var urlCancelar = '<c:out value="${linkTo[CondutorController].listar}" />';
</script>

<form id="formEscalasDeTrabalho" method="post" onsubmit="return false;" enctype="multipart/form-data">
	<div class="gt-content-box gt-for-table">
		<h3>&nbsp;&nbsp;Escala de Trabalho Vigente</h3>
		<input type="hidden" name="escalaDeTrabalho.dataVigenciaInicio" value='<fmt:formatDate pattern="dd/MM/yyyy HH:mm" value="${escala.dataVigenciaInicio.time}"/>' />
		<input type="hidden" name="escalaDeTrabalho" value="${escala.id}" />
		<table id="htmlgridDiasDeTrabalho" class="gt-table">
			<tbody id="tbody">
				<c:forEach items="${escala.diasDeTrabalho}" var="diaDeTrabalho">
					<tr>
						<th width="15%" class="obrigatorio">Dia In&iacute;cio / Fim </th>
						<td>
							<select name="diaEntrada" >
								<c:forEach items="${diaSemana.values()}" var="dia">
									<option value="${dia}" ${dia == diaDeTrabalho.getDiaEntrada() ? 'selected' : ''} ${dia == diaDeTrabalho.getDiaEntrada() ? 'class=\"selecionado \"' : ''}>${dia.nomeAbreviado}</option>
								</c:forEach>
							</select>
							<input type="text" name="horaEntrada" value='<fmt:formatDate pattern="HH:mm" value="${diaDeTrabalho.getHoraEntrada().time}"/>' size="8" class="hora selecionado" />
							at&eacute;
							<select name="diaSaida">
								<c:forEach items="${diaSemana.values()}" var="dia">
									<option value="${dia}" ${dia == diaDeTrabalho.getDiaEntrada() ? 'selected' : ''} ${dia == diaDeTrabalho.getDiaEntrada() ? 'class=\"selecionado \"' : ''}>${dia.nomeAbreviado}</option>
								</c:forEach>
							</select>
							<input type="text" name="horaSaida" value='<fmt:formatDate pattern="HH:mm" value="${diaDeTrabalho.horaSaida.time}"/>' size="8" class="hora selecionado" />
							<input type="hidden" name="id" class="selecionado" value="${diaDeTrabalho.id}" />
						</td>
						<td width="8%"><a class="linkExcluir" name="linkExcluirSelecionados" onclick="escalas.apagaLinha(this)" style="display: inline" href="#"><fmt:message key="views.botoes.excluir" /></a></td>
					</tr>
				</c:forEach>
			</tbody>
		</table>
		<div id="btngridDiasDeTrabalho" class="gt-table-buttons">
			<input type="button" id="btn-Incluir-DiasDeTrabalho" value='<fmt:message key="views.botoes.incluirNovoDia" />' class="gt-btn-medium gt-btn-left btnSelecao" />
		</div>
		<input type="hidden" name="escalaDeTrabalho.condutor.id" value="${escala.condutor.id}" />
	</div>
	<br />
	<span style="color: red; font-weight: bolder; font-size: smaller;"><fmt:message key="views.erro.preenchimentoObrigatorio" /></span>
	<div class="gt-table-buttons">
		<input type="button" id="salvar" value='<fmt:message key="views.botoes.salvar" />' class="gt-btn-medium gt-btn-left" />
		<input type="button" id="finalizar" value='<fmt:message key="views.botoes.finalizar" />' class="gt-btn-medium gt-btn-left" />
		<input type="button" id="cancelar" value='<fmt:message key="views.botoes.cancelar" />' class="gt-btn-medium gt-btn-left" />
	</div>
</form>

<div id="rowDiasDeTrabalho" style="display: none">
	<select name="diaEntrada" class="naoSelecionado">
		<c:forEach items="${diaSemana.values()}" var="dia">
			<option value="${dia}" ${dia == "SEGUNDA" ? 'selected' : ''}>${dia.nomeAbreviado}</option>
		</c:forEach>
	</select>
	<input type="text" name="horaEntrada" value="11:00" size="8" class="hora naoSelecionado" /> 
	at&eacute;
	<select name="diaSaida" class="naoSelecionado">
		<c:forEach items="${diaSemana.values()}" var="dia">
			<option value="${dia}" ${dia == "SEGUNDA" ? 'selected' : ''}>${dia.nomeAbreviado}</option>
		</c:forEach>
	</select>
	<input type="text" name="horaSaida" value="19:00" size="8" class="hora naoSelecionado" />
	<input type="hidden" name="id" class="naoSelecionado" value="${escala.id}" />
</div>

<jsp:include page="escalas.jsp"/>
<jsp:include page="../tags/calendario.jsp"/>

sigatp/src/main/webapp/WEB-INF/page/escalaDeTrabalho/listarPorCondutor.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>
<%@ taglib uri="http://localhost/jeetags" prefix="siga" %>
<%@ taglib prefix="sigatp" tagdir="/WEB-INF/tags/" %>

<siga:pagina titulo="Transportes">
	<div class="gt-bd clearfix">
		<div class="gt-content clearfix">
			<h2>${condutor.dadosParaExibicao}</h2>
			<h3>Escalas de Trabalho</h3>
			<jsp:include page="../condutor/menu.jsp"></jsp:include>
			<sigatp:erros/>
			<br/>
			<jsp:include page="form.jsp" />
			<c:choose>
				<c:when test="${escalas.size() > 0}">
					<div class="gt-content-box gt-for-table">    
					    <h3>&nbsp;&nbsp;Hist&oacute;rico das Escalas de Trabalho</h3> 
					 	<table id="htmlgrid" class="gt-table tablesorter">
					 		<thead>
						    	<tr style="font-weight: bold;">
						    	    <th>In&iacute;cio Vig&ecirc;ncia</th>
							   		<th>Fim Vig&ecirc;ncia</th>
							   		<th>Escala</th>
								</tr>
					 		</thead>
					 		<tbody>
								<c:forEach items="${escalas}" var="escala">
								   	<tr>
							    	    <td><fmt:formatDate pattern="dd/MM/yyyy HH:mm" value="${escala.dataVigenciaInicio.time}" /></td>
							    	    <td><fmt:formatDate pattern="dd/MM/yyyy HH:mm" value="${escala.dataVigenciaFim.time}" /></td>
							    		<td>${escala.escalaParaExibicao}</td>
									</tr>
								</c:forEach>
					 		</tbody>
					     </table>  
					</div>
				     <sigatp:paginacao/> 
				</c:when>
				<c:otherwise>
					<br/>
					<h3>N&atilde;o existem escalas cadastradas para este condutor.</h3>
				</c:otherwise>
			</c:choose>
		</div>
	</div>
</siga:pagina>

sigatp/src/main/webapp/WEB-INF/page/escalaDeTrabalho/listarPorCondutorSeparado.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib prefix="sigatp" tagdir="/WEB-INF/tags/"%>

<siga:pagina titulo="Transportes">
	<div class="gt-bd clearfix">
		<div class="gt-content clearfix">
			<h2>${condutor.dadosParaExibicao} - Rela&ccedil;&atilde;o de Escalas de Trabalho</h2>
			<jsp:include page="../condutor/menu.jsp" />
			<c:choose>
				<c:when test="${escalas.size()>0}">
						<div class="gt-content-box gt-for-table">     
						 	<table id="htmlgrid" class="gt-table tablesorter">
						 		<thead>
							    	<tr style="font-weight: bold;">
							    		<th width="1%" class="noSort"></th>
										<th width="1%" class="noSort"></th>
							    	    <th>In&iacute;cio Vig&ecirc;ncia</th>
								   		<th>Fim Vig&ecirc;ncia</th>
								   		<th>Escala</th>
									</tr>
						 		</thead>
						 		<tbody>
									<c:forEach items="${escalas}" var="escala">
									   	<tr>
								    		<td>
								    			<sigatp:formatarColuna operacao="editar" href="${linkTo[EscalaDeTrabalhoController].editar[escala.id]}" titulo="escala"/>
								    		</td>
								    		<td>
								    			<sigatp:formatarColuna operacao="excluir" href="${linkTo[EscalaDeTrabalhoController].excluir[escala.id]}" 
								    			onclick="javascript:return confirm('Tem certeza de que deseja excluir esta escala?');" titulo="escala"/>
								    		</td>
								    	    <td>${escala.dataVigenciaInicio?.format("dd/MM/yyyy")}</td>
								    	    <td>${escala.dataVigenciaFim?.format("dd/MM/yyyy")}</td>
								    		<td>${escala.escalaParaExibicao}</td>
										</tr>
									</c:forEach>
						 		</tbody>
						     </table>
						     <sigatp:paginacao />   
						</div>
				</c:when>
				<c:otherwise>
					<br/>
					<h3>N&atilde;o existem escalas cadastradas para este condutor.</h3>
				</c:otherwise>
			</c:choose>
			<div class="gt-table-buttons">
				<a href="${linkTo[EscalaDeTrabalhoController].incluir[condutor.id]}" class="gt-btn-medium gt-btn-left"><fmt:message key="views.botoes.incluir" /></a>
			</div>
		</div>
	</div>
</siga:pagina>

<jsp:include page="../tags/calendario.jsp"/>