sigasr/src/main/java/br/gov/jfrj/siga/sr/model/SrAcao.java
package br.gov.jfrj.siga.sr.model;

import java.util.ArrayList;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

import br.gov.jfrj.siga.base.AplicacaoException;
import br.gov.jfrj.siga.base.Texto;
import br.gov.jfrj.siga.cp.model.HistoricoSuporte;
import br.gov.jfrj.siga.model.ActiveRecord;
import br.gov.jfrj.siga.model.Assemelhavel;
import br.gov.jfrj.siga.model.Selecionavel;
import br.gov.jfrj.siga.sr.model.SrTipoAcao.SrTipoAcaoVO;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;

@Entity
@Table(name = "SR_ACAO", schema = "SIGASR")
@Cache(usage = CacheConcurrencyStrategy.TRANSACTIONAL)
public class SrAcao extends HistoricoSuporte implements SrSelecionavel, Comparable<SrAcao>,  Selecionavel {
	private static final long serialVersionUID = 8387408543308440033L;

	public static final ActiveRecord<SrAcao> AR = new ActiveRecord<>(SrAcao.class);

	@Id
	@SequenceGenerator(sequenceName = "SIGASR" +".SR_ACAO_SEQ", name = "srAcaoSeq")
	@GeneratedValue(generator = "srAcaoSeq")
	@Column(name = "ID_ACAO")
	private Long idAcao;

	@Column(name = "SIGLA_ACAO")
	private String siglaAcao;

	@Column(name = "DESCR_ACAO")
	private String descrAcao;

	@Column(name = "TITULO_ACAO")
	private String tituloAcao;

	@ManyToOne()
	@JoinColumn(name = "HIS_ID_INI", insertable = false, updatable = false)
	private SrAcao acaoInicial;

	@ManyToOne
	@JoinColumn(name = "TIPO_ACAO")
	private SrTipoAcao tipoAcao;

	@OneToMany(targetEntity = SrAcao.class, mappedBy = "acaoInicial", fetch = FetchType.LAZY)
	@OrderBy("hisDtIni desc")
	private List<SrAcao> meuAcaoHistoricoSet;

	@ManyToOne()
	@JoinColumn(name = "ID_PAI")
	private SrAcao pai;

	@OneToMany(targetEntity = SrAcao.class, mappedBy = "pai", fetch = FetchType.LAZY)
	private List<SrAcao> filhoSet;

	public SrAcao() {
		this(null, null);
	}

	public SrAcao(String descricao) {
		this(descricao, null);
	}

	public SrAcao(String sigla, String descricao) {
		this.tituloAcao = descricao;
		this.siglaAcao = sigla;
	}

	@Override
	public Long getId() {
		return this.idAcao;
	}

	public void setId(Long id) {
		idAcao = id;
	}

	@Override
	public String getSigla() {
		return this.siglaAcao;
	}

	@Override
	public String getDescricao() {
		return tituloAcao;
	}
	
	public String getDescricaoCompleta(){
		return siglaAcao + " - " + tituloAcao;
	}

	public void setDescricao(String descricao) {
		this.tituloAcao = descricao;
	}

	public List<SrAcao> getHistoricoAcao() {
		if (acaoInicial != null)
			return acaoInicial.meuAcaoHistoricoSet;
		return null;
	}

	public SrAcao getAtual() {
		if (getHisDtFim() == null)
			return this;
		List<SrAcao> sols = getHistoricoAcao();
		if (sols == null)
			return null;
		return sols.get(0);
	}

	@Override
	public boolean semelhante(Assemelhavel obj, int profundidade) {
		return false;
	}

	public SrAcao selecionar(String sigla) throws Exception {
		return selecionar(sigla, null);
	}

	public SrAcao selecionar(String sigla, List<SrAcao> listaBase)
			throws Exception {
		setSigla(sigla);
		List<SrAcao> itens = buscar(listaBase);
		if (itens.size() == 0 || itens.size() > 1)
			return null;
		return itens.get(0);

	}

	public List<SrAcao> buscar() throws Exception {
		return buscar(null);
	}

	public List<SrAcao> buscar(List<SrAcao> listaBase) throws Exception {

		List<SrAcao> lista = new ArrayList<SrAcao>();
		List<SrAcao> listaFinal = new ArrayList<SrAcao>();

		if (listaBase == null)
			lista = listar(Boolean.FALSE);
		else
			lista = listaBase;

		if ((siglaAcao == null || siglaAcao.equals(""))
				&& (tituloAcao == null || tituloAcao.equals("")))
			return lista;

		for (SrAcao acao : lista) {
			if (siglaAcao != null && !siglaAcao.equals("")
					&& !(acao.siglaAcao.contains(getSigla())))
				continue;
			if (tituloAcao != null && !tituloAcao.equals("")) {
				boolean naoAtende = false;
				for (String s : tituloAcao.toLowerCase().split("\\s"))
					if (!acao.tituloAcao.toLowerCase().contains(s))
						naoAtende = true;
				if (naoAtende)
					continue;
			}
			listaFinal.add(acao);
		}
		return listaFinal;
	}

	@Override
	public void setSigla(String sigla) {
		if (sigla == null) {
			tituloAcao = "";
			siglaAcao = "";
		} else {
			String padrao = "([0-9][0-9]).?([0-9][0-9])";
			final Pattern p1 = Pattern.compile("^" + padrao);
			final Matcher m1 = p1.matcher(sigla);
			if (m1.find()) {
				String s = "";
				for (int i = 1; i <= m1.groupCount(); i++) {
					s += m1.group(i);
					s += (i < m1.groupCount()) ? "." : "";
				}
				siglaAcao = s;
			} else
				tituloAcao = sigla;
		}
	}

	public int getNivel() {
		int camposVazios = 0;
		int pos = getSigla().indexOf(".00", 0);
		while (pos > -1) {
			camposVazios++;
			pos = getSigla().indexOf(".00", pos + 1);
		}
		return 2 - camposVazios;
	}

	public boolean isEspecifico() {
		return getNivel() == 2;
	}

	public String getSiglaSemZeros() {
		int posFimComparacao = getSigla().indexOf(".00");
		if (posFimComparacao < 0)
			posFimComparacao = getSigla().length() - 1;
		return getSigla().substring(0, posFimComparacao + 1);
	}

	public SrAcao getPaiPorSigla() {
		String sigla = getSiglaSemZeros();
		sigla = sigla.substring(0, sigla.length() - 1);
		if (sigla.lastIndexOf(".") == -1)
			return null;
		sigla = sigla.substring(0, sigla.lastIndexOf("."));
		for (int i = 0; i < 2 - (getNivel() - 1); i++) {
			sigla += ".00";
		}
		return SrAcao.AR.find("byHisDtFimIsNullAndSiglaAcao", sigla).first();
	}

	public boolean isPaiDeOuIgualA(SrAcao outraAcao) {
		if (outraAcao == null || outraAcao.getSigla() == null)
			return false;
		if (this.equals(outraAcao))
			return true;
		int posFimComparacao = getSigla().indexOf(".00");
		if (posFimComparacao < 0)
			posFimComparacao = getSigla().length() - 1;
		return outraAcao.getSigla().startsWith(
				getSigla().substring(0, posFimComparacao + 1));
	}

	public boolean isFilhoDeOuIgualA(SrAcao outroItem) {
		return outroItem.isPaiDeOuIgualA(this);
	}

	public static List<SrAcao> listar(boolean mostrarDesativados) {
		StringBuffer sb = new StringBuffer();

		if (!mostrarDesativados)
			sb.append(" hisDtFim is null");
		else {
			sb.append(" idAcao in (");
			sb.append(" SELECT max(idAcao) as idAcao FROM ");
			sb.append(" SrAcao GROUP BY hisIdIni) ");
		}

		sb.append(" order by siglaAcao ");

		return SrAcao.AR.find(sb.toString()).fetch();
	}

	@SuppressWarnings("unused")
	public String getGcTags() {
		int nivel = this.getNivel();
		String tags = "";
		SrAcao pai = this.pai;
		if (pai != null)
			tags += pai.getGcTags();
		return tags + "&tags=@sr-acao-" + nivel + "-" + getIdInicial() + ":" + getTituloSlugify();
	}

	@SuppressWarnings("unused")
	public String getGcTagAncora() {
		int nivel = this.getNivel();
		return "&tags=^sr-acao-" + nivel + "-" + getIdInicial() + ":" + getTituloSlugify();
	}

	public String getTituloSlugify() {
		return Texto.slugify(tituloAcao, true, false);
	}

	@Override
	public void salvarComHistorico() throws Exception {
		if (getNivel() > 1) {
			SrAcao pai = getPaiPorSigla();
			if (pai == null)
				throw new AplicacaoException("Ainda não há categoria para a ação a ser criada.");
			setPai(pai);
		}
		super.salvarComHistorico();
	}

	public List<SrAcao> getAcaoETodasDescendentes() {
		List<SrAcao> lista = new ArrayList<SrAcao>();
		lista.add(this);
		for (SrAcao filho : filhoSet) {
			if (filho.getHisDtFim() == null)
				lista.addAll(filho.getAcaoETodasDescendentes());
		}
		return lista;
	}

	public Long getIdAcao() {
		return idAcao;
	}

	public void setIdAcao(Long idAcao) {
		this.idAcao = idAcao;
	}

	public String getSiglaAcao() {
		return siglaAcao;
	}

	public void setSiglaAcao(String siglaAcao) {
		this.siglaAcao = siglaAcao;
	}

	public String getDescrAcao() {
		return descrAcao;
	}

	public void setDescrAcao(String descrAcao) {
		this.descrAcao = descrAcao;
	}

	public String getTituloAcao() {
		return tituloAcao;
	}

	public void setTituloAcao(String tituloAcao) {
		this.tituloAcao = tituloAcao;
	}

	public SrAcao getAcaoInicial() {
		return acaoInicial;
	}

	public void setAcaoInicial(SrAcao acaoInicial) {
		this.acaoInicial = acaoInicial;
	}

	public SrTipoAcao getTipoAcao() {
		return tipoAcao;
	}

	public void setTipoAcao(SrTipoAcao tipoAcao) {
		this.tipoAcao = tipoAcao;
	}

	public List<SrAcao> getMeuAcaoHistoricoSet() {
		return meuAcaoHistoricoSet;
	}

	public void setMeuAcaoHistoricoSet(List<SrAcao> meuAcaoHistoricoSet) {
		this.meuAcaoHistoricoSet = meuAcaoHistoricoSet;
	}

	public SrAcao getPai() {
		return pai;
	}

	public void setPai(SrAcao pai) {
		this.pai = pai;
	}

	public List<SrAcao> getFilhoSet() {
		return filhoSet;
	}

	public void setFilhoSet(List<SrAcao> filhoSet) {
		this.filhoSet = filhoSet;
	}

	@Override
	public String toString() {
		return siglaAcao + " - " + tituloAcao;
	}

	@Override
	public int compareTo(SrAcao arg0) {
		if (arg0.descrAcao == null) {
			return -1;
		} else if (this.descrAcao == null) {
			return 0;
		}
		return this.descrAcao.compareTo(arg0.descrAcao);
	}

	/**
	 * Classe que representa um V.O. de {@link SrAcao}.
	 */
	public class SrAcaoVO {

		public Long id;
		public String tituloAcao;
		public String sigla;
		public Long hisIdIni;
		public String descricao;
		public String descrAcao;
		public boolean ativo;
		public int nivel;
		public SrTipoAcaoVO tipoAcao;

		public SrAcaoVO(Long id, String sigla, String descricao, String titulo, String descrAcao,  Long hisIdIni, int nivel, boolean ativo, SrTipoAcao tipoAcao) {
			this.id = id;
			this.sigla = sigla;

sigasr/src/main/java/br/gov/jfrj/siga/sr/vraptor/AcaoController.java
package br.gov.jfrj.siga.sr.vraptor;

import static br.gov.jfrj.siga.sr.util.SrSigaPermissaoPerfil.ADM_ADMINISTRAR;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.EntityManager;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.commons.lang.StringUtils;
import org.jboss.logging.Logger;
import org.jfree.util.Log;

import br.com.caelum.vraptor.Path;
import br.com.caelum.vraptor.Resource;
import br.com.caelum.vraptor.Result;
import br.com.caelum.vraptor.view.Results;
import br.gov.jfrj.siga.Service;
import br.gov.jfrj.siga.dp.dao.CpDao;
import br.gov.jfrj.siga.gc.service.GcService;
import br.gov.jfrj.siga.sr.annotation.AssertAcesso;
import br.gov.jfrj.siga.sr.model.SrAcao;
import br.gov.jfrj.siga.sr.model.SrSolicitacao;
import br.gov.jfrj.siga.sr.model.TipoAcaoSelecao;
import br.gov.jfrj.siga.sr.validator.SrValidator;
import br.gov.jfrj.siga.vraptor.SigaObjects;

@Resource
@Path("app/acao")
public class AcaoController extends SrController {

	public AcaoController(HttpServletRequest request, HttpServletResponse response, Result result, CpDao dao, SigaObjects so, EntityManager em, SrValidator srValidator) {
		super(request, response, result, dao, so, em, srValidator);
	}

	private static final String ACAO = "acao";
	private static final String ACOES = "acoes";
	private final static Logger log = Logger.getLogger(AcaoController.class);

	@AssertAcesso(ADM_ADMINISTRAR)
	@Path("/listar")
	public void listar(boolean mostrarDesativados) throws Exception {
		List<SrAcao> acoes = SrAcao.listar(mostrarDesativados);

		result.include(ACOES, acoes);
		result.include("tipoAcaoSel", new TipoAcaoSelecao());
		result.include("mostrarDesativados", mostrarDesativados);
	}

	@Path("/listarDesativados")
	public void listarDesativados() throws Exception {
		result.redirectTo(AcaoController.class).listar(Boolean.TRUE);
	}

	@AssertAcesso(ADM_ADMINISTRAR)
	@Path("/editar")
	public void editar(Long id) throws Exception {
		SrAcao acao = new SrAcao();
		if (id != null)
			acao = SrAcao.AR.findById(id);

		result.include(ACAO, acao);
	}

	@AssertAcesso(ADM_ADMINISTRAR)
	@Path("/gravar")
	public void gravar(SrAcao acao, TipoAcaoSelecao tipoAcaoSel) throws Exception {
		validarFormEditarAcao(acao);
		acao.setTipoAcao(tipoAcaoSel.buscarObjeto());
		acao.salvarComHistorico();
		
		try{
			// Chama o webservice do SIGA-GC para atualizar as tags dos conhecimentos relacionados
	        //
	        GcService gc = Service.getGcService();
	        gc.atualizarTag(acao.getGcTags().replace("&tags=", ", ").substring(2));
			gc.atualizarTag(acao.getGcTagAncora().replace("&tags=", ", ")
					.substring(2));
		} catch(Exception e){
			Log.error("Não foi possível atualizar tags vinculadas à ação " + acao.getSigla(), e);
		}

		result.use(Results.http()).body(acao.toJson());
	}

	@AssertAcesso(ADM_ADMINISTRAR)
	@Path("/desativar")
	public void desativar(Long id, boolean mostrarDesativados) throws Exception {
		SrAcao acao = SrAcao.AR.findById(id);
		acao.finalizar();

		result.use(Results.http()).body(acao.toJson());
	}

	@AssertAcesso(ADM_ADMINISTRAR)
	@Path("/reativar")
	public void reativar(Long id, boolean mostrarDesativados) throws Exception {
		SrAcao acao = SrAcao.AR.findById(id);
		acao.salvarComHistorico();

		result.use(Results.http()).body(acao.toJson());
	}

	@Path("/selecionar")
	public void selecionar(String sigla, SrSolicitacao sol)throws Exception {
		SrAcao acao = new SrAcao().selecionar(sigla, sol != null ? sol.getAcoesDisponiveis() : null);
		result
			.forwardTo(SelecaoController.class)
			.ajaxRetorno(acao);
	}

	@Path("/buscar")
	public void buscar(String sigla, String nome, String siglaAcao, String tituloAcao, SrSolicitacao sol, String propriedade) {
		List<SrAcao> items = null;
		
		SrAcao filtro = new SrAcao();
		filtro.setSiglaAcao(siglaAcao);
		filtro.setTituloAcao(tituloAcao);

		try {
			if (sigla != null && !sigla.trim().equals(""))
				filtro.setSigla(sigla);
			
			items = filtro.buscar(sol != null
					&& (sol.getSolicitante() != null || sol.getLocal() != null) ? sol
					.getAcoesDisponiveis() : null);
			
		} catch (Exception e) {
			items = new ArrayList<SrAcao>();
		}

		result.include("items", items);
		result.include("sol", sol);
		result.include("filtro", filtro);
		result.include("nome", nome);
		result.include("propriedade", propriedade);
	}

	private void validarFormEditarAcao(SrAcao acao) {
		if (StringUtils.EMPTY.equals(acao.getSiglaAcao()))
			srValidator.addError("siglaAcao", "Código não informado");

		if (StringUtils.EMPTY.equals(acao.getTituloAcao()))
			srValidator.addError("tituloAcao", "Titulo não informado");

		if (srValidator.hasErrors())
			enviarErroValidacao();
	}
}

sigasr/src/main/webapp/WEB-INF/page/acao/listar.jsp
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://localhost/jeetags" prefix="siga"%>
<%@ taglib uri="http://localhost/sigasrtags" prefix="sigasr"%>

<siga:pagina titulo="Ações">

	<jsp:include page="../main.jsp"></jsp:include>

	<script src="/sigasr/javascripts/jquery.dataTables.min.js"></script>
	<script src="/siga/javascript/jquery-ui-1.10.3.custom/js/jquery-ui-1.10.3.custom.min.js"></script>
	<script src="/sigasr/javascripts/jquery.serializejson.min.js"></script>
	<script src="/sigasr/javascripts/jquery.populate.js"></script>
	<script src="/sigasr/javascripts/base-service.js"></script>
	
	<script src="/sigasr/javascripts/detalhe-tabela.js"></script>
	<script src="/sigasr/javascripts/jquery.maskedinput.min.js"></script>
	<script src="/sigasr/javascripts/jquery.validate.min.js"></script>
	<script src="/sigasr/javascripts/language/messages_pt_BR.min.js"></script>
	<script src="/sigasr/javascripts/moment.js"></script>

	<div class="gt-bd clearfix">
		<div class="gt-content">
			<h2>A&ccedil;&otilde;es</h2>
			<!-- content bomex -->
			<div class="gt-content-box dataTables_div">
				<div class="gt-form-row dataTables_length">
					<label>
						<siga:checkbox name="mostrarDesativados" value="${mostrarDesativados}"></siga:checkbox>
						<b>Incluir Inativas</b>
					</label>
				</div>
				<table id="acoes_table" class="gt-table display">
					<thead>
						<tr>
							<th>C&oacute;digo</th>
							<th>T&iacute;tulo</th>
							<th>Descri&ccedil;&atilde;o</th>
							<th></th>
						</tr>
					</thead>
					<tbody>
						<c:forEach items="${acoes}" var="acao">
							<tr data-json-id="${acao.idAcao}" data-json='${acao.toJson()}' onclick="acaoService.editar($(this).data('json'), 'Alterar A&ccedil;&atilde;o')" style="cursor: pointer;">
								<td>${acao.siglaAcao}</td>
								<td>
									<span style="margin-left: ${(acao.nivel-1)*2}em; <c:if test="${acao.nivel == 1}">font-weight: bold;</c:if>">
										<siga:selecionado sigla="${acao.atual.tituloAcao}" descricao="${acao.atual.descricao}"></siga:selecionado>
									</span>
								</td>
								<td>${acao.descrAcao}</td>
								<td class="acoes">
									<sigasr:desativarReativar id="${acao.idAcao}" onReativar="acaoService.reativar" onDesativar="acaoService.desativar" isAtivo="${acao.isAtivo()}"></sigasr:desativarReativar>
								</td>
							</tr>
						</c:forEach>
					</tbody>
				</table>
			</div>
			<!-- /content box -->
			<div class="gt-table-buttons">
				<a onclick="acaoService.cadastrar('Incluir A&ccedil;&atilde;o')" class="gt-btn-medium gt-btn-left">Incluir</a>
			</div>
		</div>
	</div>
	<sigasr:modal nome="acao" titulo="Cadastrar A&ccedil;&atilde;o">
		<div id="divEditarAcaoForm"><jsp:include page="editar.jsp"></jsp:include></div>
	</sigasr:modal>

</siga:pagina>

<script type="text/javascript">
	var validatorAcaoForm;
	var colunasAcao = {
			codigo: 0,
			titulo: 1,
			descrAcao: 2,
			acoes: 3
		};
	var QueryString = function () {
		// This function is anonymous, is executed immediately and
		// the return value is assigned to QueryString!
		var query_string = {};
		var query = window.location.search.substring(1);
		var vars = query.split("&");
		for (var i=0;i<vars.length;i++) {
			var pair = vars[i].split("=");
	    	// If first entry with this name
	    	if (typeof query_string[pair[0]] === "undefined") {
				query_string[pair[0]] = pair[1];
				// If second entry with this name
			} else if (typeof query_string[pair[0]] === "string") {
				var arr = [ query_string[pair[0]], pair[1] ];
				query_string[pair[0]] = arr;
				// If third or later entry with this name
			} else {
				query_string[pair[0]].push(pair[1]);
			}
		}
		return query_string;
	}();

	var opts = {
			 urlDesativar : "${linkTo[AcaoController].desativar}",
			 urlReativar : "${linkTo[AcaoController].reativar}",
			 urlGravar : "${linkTo[AcaoController].gravar}",
			 dialogCadastro : $('#acao_dialog'),
			 tabelaRegistros : $('#acoes_table'),
			 objectName : 'acao',
			 formCadastro : $('#acaoForm'),
			 mostrarDesativados : $('#checkmostrarDesativados').attr('checked') ? true : false, //QueryString.mostrarDesativados,
			 colunas : colunasAcao.acoes
	};
	
	$(document).ready(function() {
		if (QueryString.mostrarDesativados != undefined) {
			document.getElementById('checkmostrarDesativados').checked = QueryString.mostrarDesativados == 'true';
			document.getElementById('checkmostrarDesativados').value = QueryString.mostrarDesativados == 'true';
		}
			
		$("#checkmostrarDesativados").click(function() {
			jQuery.blockUI(objBlock);
			if (document.getElementById('checkmostrarDesativados').checked)
				location.href = "${linkTo[AcaoController].listar}"  + "?mostrarDesativados=true";
			else
				location.href = "${linkTo[AcaoController].listar}"  + "?mostrarDesativados=false";
		});
		
		/* Table initialization */
		opts.dataTable = $('#acoes_table').dataTable({
			stateSave : true,
			"language": {
				"emptyTable":     "N&aacute;o existem resultados",
			    "info":           "Mostrando de _START_ a _END_ do total de _TOTAL_ registros",
			    "infoEmpty":      "Mostrando de 0 a 0 do total de 0 registros",
			    "infoFiltered":   "(filtrando do total de _MAX_ registros)",
			    "infoPostFix":    "",
			    "thousands":      ".",
			    "lengthMenu":     "Mostrar _MENU_ registros",
			    "loadingRecords": "Carregando...",
			    "processing":     "Processando...",
			    "search":         "Filtrar:",
			    "zeroRecords":    "Nenhum registro encontrado",
			    "paginate": {
			        "first":      "Primeiro",
			        "last":       "&Uacute;timo",
			        "next":       "Pr&oacute;ximo",
			        "previous":   "Anterior"
			    },
			    "aria": {
			        "sortAscending":  ": clique para ordena&ccedil;&atilde;o crescente",
			        "sortDescending": ": clique para ordena&ccedil;&atilde;o decrescente"
			    }
			},
			"columnDefs": [{
				"targets": [colunasAcao.acoes],
				"searchable": false,
				"sortable" : false
			}],
			"fnRowCallback": function( nRow, aData, iDisplayIndex, iDisplayIndexFull ) {
				var acao = undefined;
				
				try {
					acao = JSON.parse($(nRow).data('json'));
				}
				catch(err) {
					acao = $(nRow).data('json');
				}
				
				if (acao) {
					if (acao.ativo == false)
						$('td', nRow).addClass('item-desativado');
					else
						$('td', nRow).removeClass('item-desativado');
				}
			}
		});
	});

	// Define a "classe" AcaoService
	function AcaoService(opts) {
		// super(opts)
		BaseService.call(this, opts);
	}
	// AcaoService extends BaseService
	AcaoService.prototype = Object.create(BaseService.prototype);
	
	var acaoService = new AcaoService(opts);
	
	acaoService.getId = function(acao) {
		return acao.id || acao['acao.idAcao'];
	}

	acaoService.editar = function(obj, title) {
		acaoService.limparTipoAcao();
		BaseService.prototype.editar.call(this, obj, title);
	}

	acaoService.cadastrar = function(title) {
        acaoService.limparTipoAcao();
        BaseService.prototype.cadastrar.call(this, title);
	}

	acaoService.limparTipoAcao = function() {
	    $("#formulario_tipoAcaoSel_id").val('');
	    $("#formulario_tipoAcaoSel_descricao").val('');
	    $("#formulario_tipoAcaoSel_sigla").val('');
	    $("#tipoAcaoSelSpan").html('');

	}

	acaoService.serializar = function(obj) {
        var query = BaseService.prototype.serializar.call(this, obj);
        return query + "&acao=" + this.getId(obj);
    }

	acaoService.getRow = function(acao) {
		var marginLeft = (acao.nivel-1) * 2,
			fontWeight = (acao.nivel == 1) ? 'bold' : 'normal',
			span = $('<span></span>');

		var spanHTML = '<span style="margin-left:{margin-left};font-weight:{font-weight}">{descricao}</span>';
		spanHTML = spanHTML.replace('{margin-left}', marginLeft + 'em');
		spanHTML = spanHTML.replace('{font-weight}', fontWeight);
		spanHTML = spanHTML.replace('{descricao}', acao.tituloAcao);
		
		return [acao.sigla, spanHTML, acao.descrAcao, 'COLUNA_ACOES'];
	}
	acaoService.onRowClick = function(acao) {
		acaoService.editar(acao, 'Alterar A&ccedil;&atilde;o');
	}

</script>